### PR TITLE
Perform movement

### PR DESCRIPTION
**Pull request by matejka9**
Refactor execute_plan and perform_movement.

### CODE REVIEW

**Comment by pavelpetrovic** [comment]
since not everybody in the group speaks Slovak, it would be nice to write comments in English only, if any. remember that clean code needs no comments.

**Comment by matejka9** [comment]
should be better now then

**Comment by pavelpetrovic** [comment]
Thanks. Have you tested this version of code? Does it execute the plan properly?

**Comment by matejka9** [comment]
#include <stdio.h>

// START TEST SIMULATION DATA
int dy = 0;
int dx = 0;

int robot_row = 0;
int robot_col = 0;

int plan_row[] = {0};
int plan_col[] = {0};

int plan_length = 1;

void right()
{
  printf("Right\n");
}

void left()
{
  printf("Left\n");
}

void forward()
{
  printf("Forward\n");
}
// END TEST SIMULATION DATA

#define MOVE_STAY  0
#define MOVE_RIGHT 1
#define MOVE_LEFT  2
#define MOVE_BACK  3

#define INDEX_UP    0
#define INDEX_DOWN  1
#define INDEX_LEFT  2
#define INDEX_RIGHT 3

int direction_corrections[4][4] = {
  {MOVE_STAY,  MOVE_BACK,  MOVE_LEFT,  MOVE_RIGHT },
  {MOVE_BACK,  MOVE_STAY,  MOVE_RIGHT, MOVE_LEFT  },
  {MOVE_RIGHT, MOVE_LEFT,  MOVE_STAY,  MOVE_BACK  },
  {MOVE_LEFT,  MOVE_RIGHT, MOVE_BACK,  MOVE_STAY  }
};

int get_move_direction_index(int y, int x) {
  if (y < 0) return INDEX_UP;
  if (y > 0) return INDEX_DOWN;
  if (x < 0) return INDEX_LEFT;
  return INDEX_RIGHT;
}

void correct_position_for_movement(int move)
{
  switch (move) {
    case MOVE_BACK:
      right();
    case MOVE_RIGHT:
      right();
      break;
    case MOVE_LEFT:
      left();
    default:
      break;
  }
}

void perform_movement(int ddy, int ddx){
  int row = get_move_direction_index(dy, dx);
  int col = get_move_direction_index(ddy, ddx);

  int move = direction_corrections[row][col];
  correct_position_for_movement(move);

  forward();
}

void execute_plan(void)
{
  int next_row, next_col, ddy, ddx;
  for (int i = 0; i < plan_length; i++) {
    next_row = plan_row[i];
    next_col = plan_col[i];

    ddy = next_row - robot_row;
    ddx = next_col - robot_col;
    perform_movement(ddy, ddx);
  }
}

// TESTS

void execute_plan_test(int number, char* expected)
{
  printf("TEST %d: Should be %s\n", number, expected);
  execute_plan();
}

void set_target_down()
{
  robot_row = 2;
  robot_col = 3;

  plan_row[0] = 3;
  plan_col[0] = 3;
}

void set_target_right()
{
  robot_row = 5;
  robot_col = 4;

  plan_row[0] = 5;
  plan_col[0] = 6;
}

void test_execute_plan_1()
{
  dy = -1;
  dx = 0;

  set_target_down();
  execute_plan_test(1, "Right, Right, Forward");
}

void test_execute_plan_2()
{
  dy = 1;
  dx = 0;

  set_target_down();
  execute_plan_test(2, "Forward");
}

void test_execute_plan_3()
{
  dy = 0;
  dx = 1;

  set_target_down();
  execute_plan_test(3, "Right, Forward");
}

void test_execute_plan_4()
{
  dy = 0;
  dx = -1;

  set_target_down();
  execute_plan_test(4, "Left, Forward");
}

void test_execute_plan_5()
{
  dy = 0;
  dx = -1;

  set_target_right();
  execute_plan_test(5, "Right, Right, Forward");
}

void test_execute_plan_6()
{
  dy = 0;
  dx = 1;

  set_target_right();
  execute_plan_test(6, "Forward");
}

int main() 
{
  printf("%d shoud be %d\n", direction_corrections[get_move_direction_index(1, 0)][get_move_direction_index(1, 0)],  MOVE_STAY);
  printf("%d shoud be %d\n", direction_corrections[get_move_direction_index(-1, 0)][get_move_direction_index(1, 0)], MOVE_BACK);
  printf("%d shoud be %d\n", direction_corrections[get_move_direction_index(1, 0)][get_move_direction_index(0, 1)],  MOVE_LEFT);
  printf("%d shoud be %d\n", direction_corrections[get_move_direction_index(0, 1)][get_move_direction_index(-1, 0)], MOVE_LEFT);
  printf("%d shoud be %d\n", direction_corrections[get_move_direction_index(0, -1)][get_move_direction_index(0, 1)], MOVE_BACK);

  test_execute_plan_1();
  test_execute_plan_2();
  test_execute_plan_3();
  test_execute_plan_4();
  test_execute_plan_5();
  test_execute_plan_6();

  return 0;
}

**Comment by matejka9** [comment]
So i did some tests, seams its working fine.

**Review by pavelpetrovic — APPROVED** [review]
teším sa na to, že to otestujeme

**Pull request merged**
